CREATE USER medusa;
CREATE DATABASE medusa;
GRANT ALL PRIVILEGES ON DATABASE medusa TO medusa;

CREATE TABLE cfs_files(ID INT PRIMARY KEY NOT NULL, CFS_DIRECTORY_ID INT, NAME VARCHAR(255), SIZE NUMERIC,
                       MTIME TIMESTAMP WITHOUT TIME ZONE, MD5_SUM VARCHAR(255), CREATED_AT TIMESTAMP WITHOUT TIME ZONE,
                       UPDATED_AT TIMESTAMP WITHOUT TIME ZONE, CONTENT_TYPE_ID INT, FILE_EXTENSION_ID INT,
                       FIXITY_CHECK_TIME TIMESTAMP WITHOUT TIME ZONE, FIXITY_CHECK_STATUS VARCHAR, FITS_SERIALIZED BOOLEAN);
CREATE TABLE cfs_directories(ID INT PRIMARY KEY NOT NULL, PATH TEXT, ROOT_CFS_DIRECTORY_ID INT, TREE_SIZE NUMERIC,
                             TREE_COUNT INT, CREATED_AT TIMESTAMP WITHOUT TIME ZONE,
                             UPDATED_AT TIMESTAMP WITHOUT TIME ZONE, PARENT_ID INT, PARENT_TYPE VARCHAR);