aws:
    account_id: "721945215539"
    region_west: "us-west-2"
    region_east : "us-east-2"
    dynamo_db:
        s3_key: "S3Key"
        file_id: "FileId"
        initial_checksum: "InitialChecksum"
        restoration_status: "RestorationStatus"
        fixity_status: "FixityStatus"
        fixity_outcome: "FixityOutcome"
        calculated_checksum: "CalculatedChecksum"
        last_updated: "LastUpdated"
        fixity_ready: "FixityReady"
        file_size: "FileSize"
        id_type: "IdType"
        current_id: "CurrentId"
        max_id: "MaxId"
        current_request_token: "CurrentRequestToken"
        job_id: "JobId"
        processed: "Processed"
        err_code: "ErrorCode"
        https_status_code: "HTTPSStatusCode"
        calculating: "CALCULATING"
        done: "DONE"
        error: "ERROR"
        requested: "REQUESTED"
        restore_posted: "ObjectRestore:Post"
        initiated: "INITIATED"
        restore_completed: "ObjectRestore:Completed"
        completed: "COMPLETED"
        restore_deleted: "ObjectRestore:Delete"
        expired: "EXPIRED"
        match: "MATCH"
        mismatch: "MISMATCH"
        true: "true"
        false: "false"
    s3:
        bulk: "Bulk"
    sqs:
        action: "action"
        file_fixity: "file_fixity"
        status: "status"
        success: "success"
        failure: "failure"
        error_message: "error_message"
        parameters: "parameters"
        checksums: "checksums"
        md5: "md5"
        found: "found"
        passthrough: "pass_through"
        cfs_file_id: "cfs_file_id"
        cfs_file_class: "cfs_file_class"
        cfs_file: "CfsFile"
