aws:
    s3:
        backup_bucket: "medusa-demo-main-backup"
        backup_bucket_arn: "arn:aws:s3:::medusa-demo-main-backup"
        batch_arn: "arn:aws:iam::721945215539:role/fixity-demo-batch-restore-role"
        batch_prefix: "fixity/BatchRestoreReports"
    sqs:
        medusa_queue_url: "https://sqs.us-east-2.amazonaws.com/721945215539/fixity-to-medusa-demo"
        s3_queue_url: "https://sqs.us-west-2.amazonaws.com/721945215539/s3-to-fixity-demo"
    dynamodb:
        fixity_table_name: "FixityDemoTable"
        batch_job_ids_table_name: "FixityDemoBatchJobsTable"
        restoration_errors_table_name : "FixityDemoRestorationErrorsTable"
        medusa_db_id_table_name: "FixityDemoMedusaDBIdTable"
        index_name: "FixityProcessingQueue"

