aws:
    s3:
        backup_bucket: "medusa-main-backup"
        backup_bucket_arn: "arn:aws:s3:::medusa-main-backup"
        batch_arn: "arn:aws:iam::721945215539:role/fixity-prod-batch-restore-role"
        batch_prefix: "prod/BatchRestoreReports"
        fixity_bucket: "medusa-fixity"
        fixity_bucket_arn: "arn:aws:s3:::medusa-fixity"
    sqs:
        medusa_queue_url: "https://sqs.us-east-2.amazonaws.com/721945215539/fixity-to-medusa-prod"
        s3_queue_url: "https://sqs.us-west-2.amazonaws.com/721945215539/s3-to-fixity-prod"
    dynamodb:
        fixity_table_name: "FixityProdTable"
        batch_job_ids_table_name: "FixityProdBatchJobsTable"
        restoration_errors_table_name : "FixityProdRestorationErrorsTable"
        medusa_db_id_table_name: "FixityProdMedusaDBIdTable"
        index_name: "FixityProcessingQueue"