aws:
    s3:
        backup_bucket: "medusa-test-main-backup"
        backup_bucket_arn: "arn:aws:s3:::medusa-test-main-backup"
        batch_arn: "arn:aws:iam::721945215539:role/fixity-test-batch-restore-role"
        batch_prefix: "fixity/BatchRestoreReports"