on:
  push:
    branches:
    - demo
    - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the tests
        run: |
            docker-compose up --build --exit-code-from fixity
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3