on:
  push:
    branches:
    - demo
    - prod

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run the tests
        run: |
            docker-compose up --build --exit-code-from fixity